### PR TITLE
fix: the sidebar can't be scroll

### LINKED ISSUE #252: The sidebar can't be scroll
The sidebar can't be scroll if it has many probes available

### PR DESCRIPTION
**Pull request by kevinhermawan**
# Symon Pull Request (PR)

Fixes #252

### CODE REVIEW

File: src/client/components/layout/index.tsx [hunk 1]
```diff
@@ -80,14 +80,14 @@ function Content({
...
 }: LayoutProps): JSX.Element {
   return (
-    <main className="flex items-start justify-between overflow-hidden">
+    <div className="flex items-start justify-between">
       <Sidebar orgName={orgName} projectID={projectID} endpoints={endpoints} />
-      <div className="pl-64 w-full">
+      <main className="pl-64 w-full">
         <Header />
-        <div className="container mx-auto px-4 py-5 sm:px-6 lg:px-7">
+        <div className="container-content container mx-auto px-4 py-5 sm:px-6 lg:px-7">
```
Comment (dennypradipta) [inline src/client/components/layout/index.tsx:87]: If there is no changes/addition for "container-content" class, kindly remove it as I don't see any additional CSS rule was made

**Review by dennypradipta — CHANGES_REQUESTED** [review]

File: src/client/components/layout/index.tsx (hunk 1 above)
Comment (dennypradipta) [reply src/client/components/layout/index.tsx:87]: Unless if you want to explain the div is the place where "container content" supposed to be, use id instead

**Review by gsukanto — APPROVED** [review]

File: src/client/components/layout/index.tsx (hunk 1 above)
Comment (kevinhermawan) [reply src/client/components/layout/index.tsx:87]: Oh yeah, I'll remove `container-content`.

**Review by dennypradipta — APPROVED** [review]
