### PR TITLE
fix: refresh token is not working

### LINKED ISSUE #238: Refresh token is not working
# Summary
The refresh token implementation is not working.

# To reproduce

- login to kaksymon
- wait 5 minutes
- reopen the root page (not the one with /project/org/...).
- data cannot be fetched.

### PR DESCRIPTION
**Pull request by kevinhermawan**
# Symon Pull Request (PR)

Fixes #238

### CODE REVIEW

File: src/client/data/requests.ts [hunk 1]
```diff
@@ -100,7 +101,10 @@ export const fetcher = async (
     },
     data: body ? JSON.stringify(body) : null,
   };
+
   const response = await axiosWithTokenInstance(config);
+  console.log("response", response);
```
Comment (nicnocquee) [inline src/client/data/requests.ts:106]: rouge console.log detected! 😈

**Review by nicnocquee — CHANGES_REQUESTED** [review]

File: src/client/data/requests.ts (hunk 1 above)
Comment (kevinhermawan) [reply src/client/data/requests.ts:106]: 😱

**Review by nicnocquee — APPROVED** [review]

**Review by dennypradipta — APPROVED** [review]
